version: '3.9'

services:
  registrar-pinchazo-sorter-api:
    build:
      context: .
    environment:
      AWS_ENDPOINT: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      QUEUE_URL: http://localstack:4566/000000000000/registrar-pinchazo-sorter-queue
    ports:
      - "3000:3000"
    depends_on:
      - localstack
    volumes:
      - .:/app
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh